/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AdminLoginRouteImport } from './routes/adminLogin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedRoutesPricingIndexRouteImport } from './routes/_authenticated/routes-pricing/index'
import { Route as AuthenticatedRelaysIndexRouteImport } from './routes/_authenticated/relays/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedDocsManagementIndexRouteImport } from './routes/_authenticated/docs-management/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedBillingRuleIndexRouteImport } from './routes/_authenticated/billing-rule/index'
import { Route as AuthenticatedAccessGroupsIndexRouteImport } from './routes/_authenticated/access-groups/index'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/adminLogin',
  path: '/adminLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoutesPricingIndexRoute =
  AuthenticatedRoutesPricingIndexRouteImport.update({
    id: '/routes-pricing/',
    path: '/routes-pricing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelaysIndexRoute =
  AuthenticatedRelaysIndexRouteImport.update({
    id: '/relays/',
    path: '/relays/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocsManagementIndexRoute =
  AuthenticatedDocsManagementIndexRouteImport.update({
    id: '/docs-management/',
    path: '/docs-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRuleIndexRoute =
  AuthenticatedBillingRuleIndexRouteImport.update({
    id: '/billing-rule/',
    path: '/billing-rule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessGroupsIndexRoute =
  AuthenticatedAccessGroupsIndexRouteImport.update({
    id: '/access-groups/',
    path: '/access-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminLogin': typeof AdminLoginRoute
  '/docs': typeof DocsRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/access-groups/': typeof AuthenticatedAccessGroupsIndexRoute
  '/billing-rule/': typeof AuthenticatedBillingRuleIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/docs-management/': typeof AuthenticatedDocsManagementIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/relays/': typeof AuthenticatedRelaysIndexRoute
  '/routes-pricing/': typeof AuthenticatedRoutesPricingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminLogin': typeof AdminLoginRoute
  '/docs': typeof DocsRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/access-groups': typeof AuthenticatedAccessGroupsIndexRoute
  '/billing-rule': typeof AuthenticatedBillingRuleIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/docs-management': typeof AuthenticatedDocsManagementIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/relays': typeof AuthenticatedRelaysIndexRoute
  '/routes-pricing': typeof AuthenticatedRoutesPricingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adminLogin': typeof AdminLoginRoute
  '/docs': typeof DocsRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/access-groups/': typeof AuthenticatedAccessGroupsIndexRoute
  '/_authenticated/billing-rule/': typeof AuthenticatedBillingRuleIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/docs-management/': typeof AuthenticatedDocsManagementIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/relays/': typeof AuthenticatedRelaysIndexRoute
  '/_authenticated/routes-pricing/': typeof AuthenticatedRoutesPricingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminLogin'
    | '/docs'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/access-groups/'
    | '/billing-rule/'
    | '/billing/'
    | '/docs-management/'
    | '/models/'
    | '/relays/'
    | '/routes-pricing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminLogin'
    | '/docs'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/access-groups'
    | '/billing-rule'
    | '/billing'
    | '/docs-management'
    | '/models'
    | '/relays'
    | '/routes-pricing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adminLogin'
    | '/docs'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/access-groups/'
    | '/_authenticated/billing-rule/'
    | '/_authenticated/billing/'
    | '/_authenticated/docs-management/'
    | '/_authenticated/models/'
    | '/_authenticated/relays/'
    | '/_authenticated/routes-pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DocsRoute: typeof DocsRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminLogin': {
      id: '/adminLogin'
      path: '/adminLogin'
      fullPath: '/adminLogin'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/routes-pricing/': {
      id: '/_authenticated/routes-pricing/'
      path: '/routes-pricing'
      fullPath: '/routes-pricing/'
      preLoaderRoute: typeof AuthenticatedRoutesPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relays/': {
      id: '/_authenticated/relays/'
      path: '/relays'
      fullPath: '/relays/'
      preLoaderRoute: typeof AuthenticatedRelaysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs-management/': {
      id: '/_authenticated/docs-management/'
      path: '/docs-management'
      fullPath: '/docs-management/'
      preLoaderRoute: typeof AuthenticatedDocsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing-rule/': {
      id: '/_authenticated/billing-rule/'
      path: '/billing-rule'
      fullPath: '/billing-rule/'
      preLoaderRoute: typeof AuthenticatedBillingRuleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-groups/': {
      id: '/_authenticated/access-groups/'
      path: '/access-groups'
      fullPath: '/access-groups/'
      preLoaderRoute: typeof AuthenticatedAccessGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessGroupsIndexRoute: typeof AuthenticatedAccessGroupsIndexRoute
  AuthenticatedBillingRuleIndexRoute: typeof AuthenticatedBillingRuleIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedDocsManagementIndexRoute: typeof AuthenticatedDocsManagementIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedRelaysIndexRoute: typeof AuthenticatedRelaysIndexRoute
  AuthenticatedRoutesPricingIndexRoute: typeof AuthenticatedRoutesPricingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessGroupsIndexRoute: AuthenticatedAccessGroupsIndexRoute,
  AuthenticatedBillingRuleIndexRoute: AuthenticatedBillingRuleIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedDocsManagementIndexRoute: AuthenticatedDocsManagementIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedRelaysIndexRoute: AuthenticatedRelaysIndexRoute,
  AuthenticatedRoutesPricingIndexRoute: AuthenticatedRoutesPricingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DocsRoute: DocsRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
