-- Baseline schema generated from the local dev database on 2026-09-14.
-- Contains all application tables, constraints, indexes, sequences, and Chinese comments.

-- Name: admin_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_account (
    username character varying(128) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: TABLE admin_account; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.admin_account IS '管理后台专用账号表；密码按当前业务要求明文存储';


--
-- Name: COLUMN admin_account.username; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_account.username IS '管理员登录账号';


--
-- Name: COLUMN admin_account.password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin_account.password IS '管理员登录密码（明文）';


--
-- Name: r2_media_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.r2_media_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_key character varying(500) NOT NULL,
    original_filename character varying(255),
    content_type character varying(100),
    file_size bigint DEFAULT 0 NOT NULL,
    content_hash character varying(64),
    width integer,
    height integer,
    status smallint DEFAULT 0 NOT NULL,
    ref_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT r2_media_ref_count_check CHECK ((ref_count >= 0)),
    CONSTRAINT r2_media_status_check CHECK (status IN (0, 1))
);


--
-- Name: relay_access_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_access_group (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_name character varying(128) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE relay_access_group; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_access_group IS '访问分组表，用于组织 Token 的模型权限与模型倍率方案';


--
-- Name: COLUMN relay_access_group.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group.id IS '分组主键ID';


--
-- Name: COLUMN relay_access_group.display_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group.display_name IS '分组显示名称';


--
-- Name: COLUMN relay_access_group.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group.enabled IS '分组是否启用';


--
-- Name: COLUMN relay_access_group.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group.created_at IS '分组创建时间';


--
-- Name: COLUMN relay_access_group.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group.updated_at IS '分组最后更新时间';


--
-- Name: relay_access_group_model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_access_group_model (
    group_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    billing_multiplier numeric(10,4) NOT NULL,
    CONSTRAINT relay_access_group_model_billing_multiplier_positive CHECK ((billing_multiplier > (0)::numeric))
);


--
-- Name: TABLE relay_access_group_model; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_access_group_model IS '访问分组与模型的权限及模型倍率关系表';


--
-- Name: COLUMN relay_access_group_model.group_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group_model.group_id IS '访问分组ID，对应relay_access_group.id';


--
-- Name: COLUMN relay_access_group_model.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group_model.model_id IS '模型唯一标识，对应relay_model.model_id';


--
-- Name: COLUMN relay_access_group_model.billing_multiplier; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_group_model.billing_multiplier IS '模型倍率：该访问分组使用对应模型时的积分计费倍率，最终积分等于模型美元成本乘每美元积分数再乘该倍率';


--
-- Name: relay_access_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_access_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label character varying(128) NOT NULL,
    group_id bigint NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token character varying(255),
    max_machine_bindings integer DEFAULT 2 NOT NULL,
    bound_machine_count integer DEFAULT 0 NOT NULL,
    max_unbind_count integer DEFAULT 2 NOT NULL,
    unbind_count integer DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    revoked_at timestamp with time zone,
    archived_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_relay_access_token_bound_machine_count CHECK ((bound_machine_count >= 0)),
    CONSTRAINT ck_relay_access_token_max_machine_bindings CHECK ((max_machine_bindings >= 0)),
    CONSTRAINT ck_relay_access_token_max_unbind_count CHECK ((max_unbind_count >= 0)),
    CONSTRAINT ck_relay_access_token_status CHECK (status IN ('ACTIVE', 'DISABLED', 'REVOKED', 'ARCHIVED')),
    CONSTRAINT ck_relay_access_token_unbind_count CHECK ((unbind_count >= 0))
);


--
-- Name: TABLE relay_access_token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_access_token IS '访问令牌表：保存客户端登录凭据，并关联模型权限分类';


--
-- Name: COLUMN relay_access_token.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.id IS '访问令牌主键，自增编号';


--
-- Name: COLUMN relay_access_token.label; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.label IS '令牌备注名称，用于标识使用人或用途';


--
-- Name: COLUMN relay_access_token.group_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.group_id IS '所属模型权限分类编号，关联 relay_access_group.id';


--
-- Name: COLUMN relay_access_token.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.enabled IS '是否启用：true 启用，false 禁用；禁用后不可登录或调用';


--
-- Name: COLUMN relay_access_token.expires_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.expires_at IS '令牌过期时间（含时区），为空表示不设过期时间';


--
-- Name: COLUMN relay_access_token.last_used_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.last_used_at IS '最近一次成功认证时间（含时区），未使用时为空';


--
-- Name: COLUMN relay_access_token.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.created_at IS '令牌创建时间（含时区），默认当前时间';


--
-- Name: COLUMN relay_access_token.token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.token IS '明文访问令牌，唯一；客户端提交后由后端查库校验，历史未补录记录可为空且不可登录';


--
-- Name: COLUMN relay_access_token.max_machine_bindings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.max_machine_bindings IS '该Token最多允许同时绑定的机器码数量；0表示不限制，默认2台';


--
-- Name: COLUMN relay_access_token.bound_machine_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.bound_machine_count IS '该Token当前已绑定的机器码数量，由登录绑定和解绑操作原子维护';


--
-- Name: COLUMN relay_access_token.max_unbind_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.max_unbind_count IS '该Token最多允许用户主动解绑的次数；0表示禁止解绑，默认2次';


--
-- Name: COLUMN relay_access_token.unbind_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.unbind_count IS '该Token已经执行的用户主动解绑次数，用于计算剩余可解绑次数';


--
-- Name: COLUMN relay_access_token.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.status IS 'Token生命周期：ACTIVE正常、DISABLED停用可恢复、REVOKED永久撤销、ARCHIVED归档隐藏';


--
-- Name: COLUMN relay_access_token.revoked_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.revoked_at IS 'Token永久撤销时间';


--
-- Name: COLUMN relay_access_token.archived_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.archived_at IS 'Token归档时间；归档后默认不在管理列表展示';


--
-- Name: COLUMN relay_access_token.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token.updated_at IS 'Token最后管理更新时间';


--
-- Name: relay_access_token_machine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_access_token_machine (
    access_token_id bigint NOT NULL,
    machine_id character varying(255) NOT NULL,
    bound_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: TABLE relay_access_token_machine; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_access_token_machine IS '访问Token与客户端机器码的当前绑定关系；绑定和解绑记录直接持久化到PostgreSQL';


--
-- Name: COLUMN relay_access_token_machine.access_token_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token_machine.access_token_id IS '访问Token主键ID';


--
-- Name: COLUMN relay_access_token_machine.machine_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token_machine.machine_id IS '客户端稳定机器码，由Kiro RelayRouter登录时提交';


--
-- Name: COLUMN relay_access_token_machine.bound_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token_machine.bound_at IS '该机器码首次绑定时间';


--
-- Name: COLUMN relay_access_token_machine.last_used_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_access_token_machine.last_used_at IS '该机器码最近一次成功认证时间';


--
-- Name: relay_billing_outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_billing_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_key character varying(192) NOT NULL,
    request_id character varying(128) NOT NULL,
    status character varying(16) DEFAULT 'NEW'::character varying NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    published_at timestamp with time zone,
    last_error character varying(512),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT relay_billing_outbox_status_valid CHECK (status IN ('NEW', 'PUBLISHED'))
);


--
-- Name: TABLE relay_billing_outbox; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_billing_outbox IS '计费结算事件事务发件箱，保证用量落库后RabbitMQ短暂故障不会丢账';


--
-- Name: COLUMN relay_billing_outbox.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.id IS '发件箱主键ID';


--
-- Name: COLUMN relay_billing_outbox.event_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.event_key IS '结算事件幂等键';


--
-- Name: COLUMN relay_billing_outbox.request_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.request_id IS '需要结算的AI请求ID';


--
-- Name: COLUMN relay_billing_outbox.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.status IS '发布状态：NEW或PUBLISHED';


--
-- Name: COLUMN relay_billing_outbox.attempts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.attempts IS '已尝试发布次数';


--
-- Name: COLUMN relay_billing_outbox.next_attempt_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.next_attempt_at IS '下次允许重试发布的时间';


--
-- Name: COLUMN relay_billing_outbox.published_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.published_at IS '成功投递到RabbitMQ的时间';


--
-- Name: COLUMN relay_billing_outbox.last_error; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.last_error IS '最近一次发布失败原因';


--
-- Name: COLUMN relay_billing_outbox.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_outbox.created_at IS '发件箱创建时间';


--
-- Name: relay_billing_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_billing_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL,
    points_per_usd numeric(20,8) NOT NULL,
    effective_from timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    effective_to timestamp with time zone,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_relay_billing_rule_period CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
    CONSTRAINT ck_relay_billing_rule_points_per_usd CHECK ((points_per_usd > (0)::numeric))
);


--
-- Name: TABLE relay_billing_rule; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_billing_rule IS '平台全局积分计费规则表，用于定义上游模型美元成本与平台积分之间的基础换算关系，并保留历史版本';


--
-- Name: COLUMN relay_billing_rule.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.id IS '计费规则主键ID';


--
-- Name: COLUMN relay_billing_rule.version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.version IS '计费规则版本号，每次修改创建新版本，不覆盖历史规则';


--
-- Name: COLUMN relay_billing_rule.points_per_usd; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.points_per_usd IS '每1美元实际上游模型成本对应的平台基础积分数量，例如10表示1 USD成本换算为10基础积分';


--
-- Name: COLUMN relay_billing_rule.effective_from; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.effective_from IS '当前规则开始生效时间';


--
-- Name: COLUMN relay_billing_rule.effective_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.effective_to IS '当前规则停止生效时间，NULL表示当前仍然有效';


--
-- Name: COLUMN relay_billing_rule.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.enabled IS '该规则是否允许作为有效计费规则使用';


--
-- Name: COLUMN relay_billing_rule.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.created_at IS '规则创建时间';


--
-- Name: COLUMN relay_billing_rule.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_billing_rule.updated_at IS '规则最后更新时间';


--
-- Name: relay_configuration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_configuration (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    base_url character varying(2048) NOT NULL,
    api_key text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name character varying(128) NOT NULL,
    provider character varying(64) DEFAULT 'openai-compatible'::character varying NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    weight integer DEFAULT 100 NOT NULL,
    health_status character varying(32) DEFAULT 'UNKNOWN'::character varying NOT NULL,
    failure_count integer DEFAULT 0 NOT NULL,
    failure_threshold integer DEFAULT 3 NOT NULL,
    connect_timeout_ms integer DEFAULT 5000 NOT NULL,
    read_timeout_ms integer DEFAULT 120000 NOT NULL,
    max_concurrency integer DEFAULT 0 NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    last_health_check_at timestamp with time zone,
    last_health_latency_ms bigint,
    last_success_at timestamp with time zone,
    last_failure_at timestamp with time zone,
    protocol_strategy character varying(32) DEFAULT 'AUTO'::character varying NOT NULL,
    CONSTRAINT ck_relay_configuration_connect_timeout CHECK ((connect_timeout_ms > 0)),
    CONSTRAINT ck_relay_configuration_failure_threshold CHECK ((failure_threshold > 0)),
    CONSTRAINT ck_relay_configuration_health_status CHECK (health_status IN ('UNKNOWN', 'UP', 'DOWN')),
    CONSTRAINT ck_relay_configuration_max_concurrency CHECK ((max_concurrency >= 0)),
    CONSTRAINT ck_relay_configuration_priority CHECK ((priority >= 0)),
    CONSTRAINT ck_relay_configuration_protocol_strategy CHECK (protocol_strategy IN ('AUTO', 'OPENAI_SMART', 'ANTHROPIC_SMART')),
    CONSTRAINT ck_relay_configuration_read_timeout CHECK ((read_timeout_ms > 0)),
    CONSTRAINT ck_relay_configuration_weight CHECK ((weight > 0))
);


--
-- Name: TABLE relay_configuration; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_configuration IS '上游中转配置表；每条记录代表一个可独立调度的中转站账号或API Key';


--
-- Name: COLUMN relay_configuration.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.id IS '中转配置主键ID';


--
-- Name: COLUMN relay_configuration.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.enabled IS '管理员是否允许该配置参与调度；false表示主动下线';


--
-- Name: COLUMN relay_configuration.base_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.base_url IS '上游API基础地址，例如https://relay.example.com/v1';


--
-- Name: COLUMN relay_configuration.api_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.api_key IS '上游API访问密钥；仅后端使用，不向下游接口返回';


--
-- Name: COLUMN relay_configuration.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.created_at IS '配置创建时间';


--
-- Name: COLUMN relay_configuration.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.updated_at IS '配置最后修改时间';


--
-- Name: COLUMN relay_configuration.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.name IS '配置名称，供管理员识别同一中转站的不同账号或API Key';


--
-- Name: COLUMN relay_configuration.provider; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.provider IS '上游协议类型，当前支持openai-compatible';


--
-- Name: COLUMN relay_configuration.priority; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.priority IS '调度优先级，数字越小越优先；仅在最优可用优先级内进行加权选择';


--
-- Name: COLUMN relay_configuration.weight; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.weight IS '同优先级配置的负载权重，数值越大被选中的概率越高';


--
-- Name: COLUMN relay_configuration.health_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.health_status IS '最近一次后台健康检查状态：UNKNOWN、UP或DOWN';


--
-- Name: COLUMN relay_configuration.failure_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.failure_count IS '连续健康检查或可归因于上游的请求失败次数';


--
-- Name: COLUMN relay_configuration.failure_threshold; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.failure_threshold IS '连续失败达到该次数后将配置标记为DOWN并停止承接请求';


--
-- Name: COLUMN relay_configuration.connect_timeout_ms; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.connect_timeout_ms IS '连接该上游的超时时间，单位毫秒';


--
-- Name: COLUMN relay_configuration.read_timeout_ms; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.read_timeout_ms IS '单次上游流式请求的最大读取时间，单位毫秒';


--
-- Name: COLUMN relay_configuration.max_concurrency; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.max_concurrency IS '该配置允许的最大在途请求数，0表示不限制';


--
-- Name: COLUMN relay_configuration.version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.version IS '配置乐观锁版本号，每次管理修改时递增';


--
-- Name: COLUMN relay_configuration.last_health_check_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.last_health_check_at IS '最近一次后台GET /models健康检查完成时间';


--
-- Name: COLUMN relay_configuration.last_health_latency_ms; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.last_health_latency_ms IS '最近一次健康检查耗时，单位毫秒';


--
-- Name: COLUMN relay_configuration.last_success_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.last_success_at IS '最近一次上游请求或健康检查成功时间';


--
-- Name: COLUMN relay_configuration.last_failure_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.last_failure_at IS '最近一次上游请求或健康检查失败时间';


--
-- Name: COLUMN relay_configuration.protocol_strategy; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration.protocol_strategy IS '协议选择策略：AUTO、OPENAI_SMART、ANTHROPIC_SMART或MANUAL；不代表最终请求协议';


--
-- Name: relay_configuration_model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_configuration_model (
    configuration_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    upstream_model_id character varying(255) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    priority_override integer,
    weight_override integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_relay_configuration_model_priority_override CHECK (((priority_override IS NULL) OR (priority_override >= 0))),
    CONSTRAINT ck_relay_configuration_model_upstream_model_id_nonblank CHECK ((TRIM(BOTH FROM upstream_model_id) <> ''::text)),
    CONSTRAINT ck_relay_configuration_model_weight_override CHECK (((weight_override IS NULL) OR (weight_override > 0)))
);


--
-- Name: TABLE relay_configuration_model; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_configuration_model IS '中转站与模型关联表，包含上游别名及模型级路由覆盖';


--
-- Name: COLUMN relay_configuration_model.configuration_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.configuration_id IS '中转配置ID，对应relay_configuration.id';


--
-- Name: COLUMN relay_configuration_model.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.model_id IS '该中转配置可处理的上游模型ID，对应relay_model.model_id';


--
-- Name: COLUMN relay_configuration_model.upstream_model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.upstream_model_id IS '实际发送给该中转站的模型ID';


--
-- Name: COLUMN relay_configuration_model.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.enabled IS '该中转站是否允许调用此模型';


--
-- Name: COLUMN relay_configuration_model.priority_override; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.priority_override IS '模型级优先级，NULL时使用中转站默认值';


--
-- Name: COLUMN relay_configuration_model.weight_override; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model.weight_override IS '模型级权重，NULL时使用中转站默认值';


--
-- Name: relay_configuration_model_pricing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_configuration_model_pricing (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    configuration_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_write_input_price numeric(20,8) DEFAULT 0 CONSTRAINT relay_configuration_model_pric_cache_write_input_price_not_null NOT NULL,
    output_price numeric(20,8) DEFAULT 0 NOT NULL,
    pricing_unit bigint DEFAULT 1000000 NOT NULL,
    currency character varying(8) DEFAULT 'USD'::character varying NOT NULL,
    price_source character varying(32) DEFAULT 'relay'::character varying NOT NULL,
    min_input_tokens bigint DEFAULT 0 NOT NULL,
    max_input_tokens bigint,
    effective_from timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    effective_to timestamp with time zone,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_relay_configuration_model_pricing_currency_usd CHECK (((currency)::text = 'USD'::text)),
    CONSTRAINT ck_relay_configuration_model_pricing_nonnegative CHECK (((input_price >= (0)::numeric) AND (cache_input_price >= (0)::numeric) AND (cache_write_input_price >= (0)::numeric) AND (output_price >= (0)::numeric))),
    CONSTRAINT ck_relay_configuration_model_pricing_period_valid CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
    CONSTRAINT ck_relay_configuration_model_pricing_source_nonblank CHECK ((TRIM(BOTH FROM price_source) <> ''::text)),
    CONSTRAINT ck_relay_configuration_model_pricing_tier_valid CHECK (((min_input_tokens >= 0) AND ((max_input_tokens IS NULL) OR (max_input_tokens >= min_input_tokens)))),
    CONSTRAINT ck_relay_configuration_model_pricing_unit_positive CHECK ((pricing_unit > 0))
);


--
-- Name: TABLE relay_configuration_model_pricing; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_configuration_model_pricing IS '中转站模型价格表；有效记录优先于relay_model_pricing，缺失时回退到官方或全局价格';


--
-- Name: COLUMN relay_configuration_model_pricing.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.id IS '中转站模型价格记录主键ID';


--
-- Name: COLUMN relay_configuration_model_pricing.configuration_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.configuration_id IS '中转站配置ID，对应relay_configuration.id';


--
-- Name: COLUMN relay_configuration_model_pricing.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.model_id IS '平台统一模型ID，与configuration_id共同对应relay_configuration_model关系';


--
-- Name: COLUMN relay_configuration_model_pricing.input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.input_price IS '普通输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_configuration_model_pricing.cache_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.cache_input_price IS '缓存读取输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_configuration_model_pricing.cache_write_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.cache_write_input_price IS '缓存写入输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_configuration_model_pricing.output_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.output_price IS '输出Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_configuration_model_pricing.pricing_unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.pricing_unit IS '价格对应的Token数量，默认1000000';


--
-- Name: COLUMN relay_configuration_model_pricing.currency; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.currency IS '价格币种，当前计费仅支持USD';


--
-- Name: COLUMN relay_configuration_model_pricing.price_source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.price_source IS '价格来源标识，默认relay；会保存到用量记录作为计费快照';


--
-- Name: COLUMN relay_configuration_model_pricing.min_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.min_input_tokens IS '该价格阶梯适用的最小总输入Token数，包含普通、缓存读取和缓存写入';


--
-- Name: COLUMN relay_configuration_model_pricing.max_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.max_input_tokens IS '该价格阶梯适用的最大总输入Token数，NULL表示无上限';


--
-- Name: COLUMN relay_configuration_model_pricing.effective_from; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.effective_from IS '价格版本开始生效时间';


--
-- Name: COLUMN relay_configuration_model_pricing.effective_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.effective_to IS '价格版本失效时间，NULL表示无预设失效时间';


--
-- Name: COLUMN relay_configuration_model_pricing.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.enabled IS '价格版本是否启用';


--
-- Name: COLUMN relay_configuration_model_pricing.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.created_at IS '价格记录创建时间';


--
-- Name: COLUMN relay_configuration_model_pricing.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_configuration_model_pricing.updated_at IS '价格记录最后更新时间';


--
-- Name: relay_configuration_model_protocol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_configuration_model_protocol (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    configuration_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    protocol_id bigint NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    capabilities json,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_rcmp_priority CHECK ((priority >= 0))
);


--
-- Name: TABLE relay_configuration_model_protocol; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_configuration_model_protocol IS 'Relay×Model的协议限制与能力覆盖；没有记录时继承中转站协议';


--
-- Name: relay_configuration_protocol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_configuration_protocol (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    configuration_id bigint NOT NULL,
    protocol_code character varying(64) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 100 NOT NULL,
    path_override character varying(255),
    text_supported boolean DEFAULT true NOT NULL,
    image_supported boolean DEFAULT false NOT NULL,
    pdf_supported boolean DEFAULT false NOT NULL,
    tool_use_supported boolean DEFAULT false NOT NULL,
    tool_result_supported boolean DEFAULT false NOT NULL,
    streaming_supported boolean DEFAULT true NOT NULL,
    prompt_cache_supported boolean DEFAULT false NOT NULL,
    verification_status character varying(32) DEFAULT 'UNVERIFIED'::character varying NOT NULL,
    last_verified_at timestamp with time zone,
    last_verification_message character varying(2000),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_relay_protocol_code CHECK (protocol_code IN ('OPENAI_CHAT_COMPLETIONS', 'OPENAI_RESPONSES', 'ANTHROPIC_MESSAGES')),
    CONSTRAINT ck_relay_protocol_path CHECK (path_override IS NULL OR (substring(path_override, 1, 1) = '/' AND POSITION('://' IN path_override) = 0)),
    CONSTRAINT ck_relay_protocol_priority CHECK ((priority >= 0)),
    CONSTRAINT ck_relay_protocol_verification CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED', 'FAILED'))
);


--
-- Name: TABLE relay_configuration_protocol; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_configuration_protocol IS '中转站实际开放的模型请求协议及能力';


--
-- Name: relay_doc_article; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_doc_article (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    content_html text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'DRAFT'::character varying NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT relay_doc_article_status_check CHECK (status IN ('DRAFT', 'PUBLISHED'))
);


--
-- Name: relay_doc_asset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_doc_asset (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    article_id bigint,
    object_key character varying(1024) NOT NULL,
    public_url character varying(2048) NOT NULL,
    original_filename character varying(512) NOT NULL,
    content_type character varying(128) NOT NULL,
    file_size bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: relay_doc_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_doc_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: relay_model; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_model (
    model_id character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE relay_model; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_model IS '平台统一模型主数据';


--
-- Name: COLUMN relay_model.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model.model_id IS '中转站真实模型唯一标识，仅后端使用';


--
-- Name: COLUMN relay_model.display_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model.display_name IS '向客户端展示的模型名称';


--
-- Name: COLUMN relay_model.sort_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model.sort_order IS '模型排列顺序，数值越小越靠前';


--
-- Name: COLUMN relay_model.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model.enabled IS '模型是否启用';


--
-- Name: relay_model_pricing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_model_pricing (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_id character varying(255) NOT NULL,
    input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_write_input_price numeric(20,8) DEFAULT 0 NOT NULL,
    output_price numeric(20,8) DEFAULT 0 NOT NULL,
    pricing_unit bigint DEFAULT 1000000 NOT NULL,
    currency character varying(8) DEFAULT 'USD'::character varying NOT NULL,
    price_source character varying(32) DEFAULT 'official'::character varying NOT NULL,
    effective_from timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    effective_to timestamp with time zone,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    min_input_tokens bigint DEFAULT 0 NOT NULL,
    max_input_tokens bigint,
    CONSTRAINT relay_model_pricing_currency_usd CHECK (((currency)::text = 'USD'::text)),
    CONSTRAINT relay_model_pricing_nonnegative CHECK (((input_price >= (0)::numeric) AND (cache_input_price >= (0)::numeric) AND (cache_write_input_price >= (0)::numeric) AND (output_price >= (0)::numeric))),
    CONSTRAINT relay_model_pricing_period_valid CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
    CONSTRAINT relay_model_pricing_source_nonblank CHECK ((TRIM(BOTH FROM price_source) <> ''::text)),
    CONSTRAINT relay_model_pricing_tier_valid CHECK (((min_input_tokens >= 0) AND ((max_input_tokens IS NULL) OR (max_input_tokens >= min_input_tokens)))),
    CONSTRAINT relay_model_pricing_unit_positive CHECK ((pricing_unit > 0))
);


--
-- Name: TABLE relay_model_pricing; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_model_pricing IS '模型官方或全局参考价格';


--
-- Name: COLUMN relay_model_pricing.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.id IS '模型价格记录主键ID';


--
-- Name: COLUMN relay_model_pricing.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.model_id IS '模型真实唯一标识，与relay_model.model_id一致；不设置外键以保留已下架模型的历史价格';


--
-- Name: COLUMN relay_model_pricing.input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.input_price IS '普通输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_model_pricing.cache_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.cache_input_price IS '缓存读取输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_model_pricing.cache_write_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.cache_write_input_price IS '缓存写入输入Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_model_pricing.output_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.output_price IS '模型输出Token价格，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_model_pricing.pricing_unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.pricing_unit IS '价格对应的Token数量，默认1000000';


--
-- Name: COLUMN relay_model_pricing.currency; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.currency IS '价格币种，当前计费仅支持USD';


--
-- Name: COLUMN relay_model_pricing.price_source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.price_source IS '价格来源，例如official或relay';


--
-- Name: COLUMN relay_model_pricing.effective_from; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.effective_from IS '价格版本开始生效时间';


--
-- Name: COLUMN relay_model_pricing.effective_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.effective_to IS '价格版本失效时间，NULL表示无预设失效时间';


--
-- Name: COLUMN relay_model_pricing.enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.enabled IS '价格版本是否启用';


--
-- Name: COLUMN relay_model_pricing.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.created_at IS '价格记录创建时间';


--
-- Name: COLUMN relay_model_pricing.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.updated_at IS '价格记录最后更新时间';


--
-- Name: COLUMN relay_model_pricing.min_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.min_input_tokens IS '该价格阶梯适用的最小总输入Token数，包含普通、缓存读取和缓存写入';


--
-- Name: COLUMN relay_model_pricing.max_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_model_pricing.max_input_tokens IS '该价格阶梯适用的最大总输入Token数，NULL表示无上限';


--
-- Name: relay_point_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_point_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_key character varying(192) NOT NULL,
    access_token_id bigint NOT NULL,
    request_id character varying(128),
    entry_type character varying(32) NOT NULL,
    available_delta numeric(20,8) NOT NULL,
    frozen_delta numeric(20,8) NOT NULL,
    available_after numeric(20,8) NOT NULL,
    frozen_after numeric(20,8) NOT NULL,
    note character varying(512),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT relay_point_ledger_type_valid CHECK (entry_type IN ('GRANT', 'FREEZE', 'SETTLE', 'RELEASE', 'ADJUST', 'REFUND'))
);


--
-- Name: TABLE relay_point_ledger; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_point_ledger IS '不可重复执行的Token积分账变流水，用于审计、对账和恢复钱包';


--
-- Name: COLUMN relay_point_ledger.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.id IS '积分流水主键ID';


--
-- Name: COLUMN relay_point_ledger.event_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.event_key IS '账变幂等键，同一业务事件只允许入账一次';


--
-- Name: COLUMN relay_point_ledger.access_token_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.access_token_id IS '发生账变的访问Token ID';


--
-- Name: COLUMN relay_point_ledger.request_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.request_id IS '关联的AI请求ID，人工充值时可为NULL';


--
-- Name: COLUMN relay_point_ledger.entry_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.entry_type IS '账变类型：发放、冻结、结算、释放、调整或退费';


--
-- Name: COLUMN relay_point_ledger.available_delta; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.available_delta IS '本次对可用积分的增减值';


--
-- Name: COLUMN relay_point_ledger.frozen_delta; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.frozen_delta IS '本次对冻结积分的增减值';


--
-- Name: COLUMN relay_point_ledger.available_after; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.available_after IS '账变后的可用积分快照';


--
-- Name: COLUMN relay_point_ledger.frozen_after; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.frozen_after IS '账变后的冻结积分快照';


--
-- Name: COLUMN relay_point_ledger.note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.note IS '账变说明';


--
-- Name: COLUMN relay_point_ledger.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_point_ledger.created_at IS '账变时间';


--
-- Name: relay_token_wallet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_token_wallet (
    access_token_id bigint NOT NULL,
    available_points numeric(20,8) DEFAULT 0 NOT NULL,
    frozen_points numeric(20,8) DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT relay_token_wallet_frozen_nonnegative CHECK ((frozen_points >= (0)::numeric))
);


--
-- Name: TABLE relay_token_wallet; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_token_wallet IS '访问Token积分钱包当前状态；用于原子预冻结和扣费，账变历史以积分流水为准';


--
-- Name: COLUMN relay_token_wallet.access_token_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.access_token_id IS '访问Token ID，同时为钱包主键';


--
-- Name: COLUMN relay_token_wallet.available_points; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.available_points IS '当前可用积分；结算后可能短暂为负，之后的请求将被拦截';


--
-- Name: COLUMN relay_token_wallet.frozen_points; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.frozen_points IS '已被进行中请求预占的积分';


--
-- Name: COLUMN relay_token_wallet.version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.version IS '钱包变更版本号，便于缓存一致性和排查';


--
-- Name: COLUMN relay_token_wallet.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.created_at IS '钱包创建时间';


--
-- Name: COLUMN relay_token_wallet.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_token_wallet.updated_at IS '钱包最后变更时间';


--
-- Name: relay_usage_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relay_usage_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id character varying(128) NOT NULL,
    access_token_id bigint NOT NULL,
    group_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    input_tokens bigint DEFAULT 0 NOT NULL,
    cache_input_tokens bigint DEFAULT 0 NOT NULL,
    cache_write_input_tokens bigint DEFAULT 0 NOT NULL,
    output_tokens bigint DEFAULT 0 NOT NULL,
    input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_input_price numeric(20,8) DEFAULT 0 NOT NULL,
    cache_write_input_price numeric(20,8) DEFAULT 0 NOT NULL,
    output_price numeric(20,8) DEFAULT 0 NOT NULL,
    pricing_unit bigint DEFAULT 1000000 NOT NULL,
    currency character varying(8) DEFAULT 'USD'::character varying NOT NULL,
    price_source character varying(32) DEFAULT 'unconfigured'::character varying NOT NULL,
    provider_cost_usd numeric(20,10) DEFAULT 0 NOT NULL,
    tool_cost_usd numeric(20,10) DEFAULT 0 NOT NULL,
    points_per_usd numeric(20,8) NOT NULL,
    billing_multiplier numeric(10,4) DEFAULT 1.0000 NOT NULL,
    charged_points numeric(20,8) DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'PENDING'::character varying NOT NULL,
    error_code character varying(64),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at timestamp with time zone,
    reserved_points numeric(20,8) DEFAULT 0 NOT NULL,
    price_tier_min_input_tokens bigint DEFAULT 0 NOT NULL,
    relay_configuration_id bigint,
    requested_model_id character varying(255),
    upstream_model_id character varying(255),
    reported_model_id character varying(255),
    upstream_model_source character varying(32) DEFAULT 'UNKNOWN'::character varying NOT NULL,
    protocol_code character varying(64),
    CONSTRAINT ck_relay_usage_protocol_code CHECK (protocol_code IS NULL OR protocol_code IN ('OPENAI_CHAT_COMPLETIONS', 'OPENAI_RESPONSES', 'ANTHROPIC_MESSAGES')),
    CONSTRAINT relay_usage_record_cost_nonnegative CHECK (((provider_cost_usd >= (0)::numeric) AND (tool_cost_usd >= (0)::numeric) AND (charged_points >= (0)::numeric))),
    CONSTRAINT relay_usage_record_currency_usd CHECK (((currency)::text = 'USD'::text)),
    CONSTRAINT relay_usage_record_points_rate_positive CHECK (((points_per_usd > (0)::numeric) AND (billing_multiplier > (0)::numeric))),
    CONSTRAINT relay_usage_record_pricing_unit_positive CHECK ((pricing_unit > 0)),
    CONSTRAINT relay_usage_record_status_valid CHECK (status IN ('PENDING', 'READY_TO_SETTLE', 'SETTLED', 'COMPLETED', 'UNPRICED', 'MISSING_USAGE', 'FAILED', 'REFUNDED')),
    CONSTRAINT relay_usage_record_token_counts_nonnegative CHECK (((input_tokens >= 0) AND (cache_input_tokens >= 0) AND (cache_write_input_tokens >= 0) AND (output_tokens >= 0))),
    CONSTRAINT relay_usage_record_upstream_model_source_valid CHECK (upstream_model_source IN ('RESPONSE', 'CONFIG', 'UNKNOWN'))
);


--
-- Name: TABLE relay_usage_record; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.relay_usage_record IS 'AI请求Token用量和积分消费流水，保存请求发生时的价格及倍率快照';


--
-- Name: COLUMN relay_usage_record.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.id IS '消费流水主键ID';


--
-- Name: COLUMN relay_usage_record.request_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.request_id IS 'AI请求唯一ID，用于追踪和防止重复记账';


--
-- Name: COLUMN relay_usage_record.access_token_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.access_token_id IS '发起请求的访问Token记录ID，对应relay_access_token.id';


--
-- Name: COLUMN relay_usage_record.group_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.group_id IS '请求发生时Token所属分组ID，对应relay_access_group.id';


--
-- Name: COLUMN relay_usage_record.model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.model_id IS '平台统一模型ID，对应relay_model.model_id；不是上游中转站内部真实执行模型';


--
-- Name: COLUMN relay_usage_record.input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.input_tokens IS '本次普通输入Token数量，不包含缓存读取和缓存写入Token';


--
-- Name: COLUMN relay_usage_record.cache_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.cache_input_tokens IS '本次缓存命中读取的输入Token数量';


--
-- Name: COLUMN relay_usage_record.cache_write_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.cache_write_input_tokens IS '本次写入缓存的输入Token数量';


--
-- Name: COLUMN relay_usage_record.output_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.output_tokens IS '本次模型输出Token数量';


--
-- Name: COLUMN relay_usage_record.input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.input_price IS '请求发生时普通输入Token价格快照，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_usage_record.cache_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.cache_input_price IS '请求发生时缓存读取Token价格快照，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_usage_record.cache_write_input_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.cache_write_input_price IS '请求发生时缓存写入Token价格快照，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_usage_record.output_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.output_price IS '请求发生时输出Token价格快照，单位为美元/定价Token单位';


--
-- Name: COLUMN relay_usage_record.pricing_unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.pricing_unit IS '价格快照对应的Token数量单位';


--
-- Name: COLUMN relay_usage_record.currency; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.currency IS '计费币种快照，当前仅支持USD';


--
-- Name: COLUMN relay_usage_record.price_source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.price_source IS '价格来源快照；unconfigured表示请求时未配置有效价格';


--
-- Name: COLUMN relay_usage_record.provider_cost_usd; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.provider_cost_usd IS 'Token费用与工具费用相加后的本次供应商美元总成本';


--
-- Name: COLUMN relay_usage_record.tool_cost_usd; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.tool_cost_usd IS '上游usage明确返回的工具调用美元成本，未返回时为0';


--
-- Name: COLUMN relay_usage_record.points_per_usd; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.points_per_usd IS '请求开始时生效的每美元积分换算规则快照，历史账单永远不按当前规则重算';


--
-- Name: COLUMN relay_usage_record.billing_multiplier; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.billing_multiplier IS '请求发生时采用的模型倍率快照';


--
-- Name: COLUMN relay_usage_record.charged_points; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.charged_points IS '最终计费积分，等于供应商美元成本乘每美元积分数再乘模型倍率';


--
-- Name: COLUMN relay_usage_record.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.status IS '计费状态：PENDING、READY_TO_SETTLE、SETTLED、UNPRICED、MISSING_USAGE、FAILED或REFUNDED';


--
-- Name: COLUMN relay_usage_record.error_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.error_code IS '失败类别；成功时为NULL';


--
-- Name: COLUMN relay_usage_record.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.created_at IS '请求开始计费记录的创建时间';


--
-- Name: COLUMN relay_usage_record.completed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.completed_at IS '请求完成、失败或结算结束时间';


--
-- Name: COLUMN relay_usage_record.reserved_points; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.reserved_points IS '请求发往上游前从可用余额预冻结的积分快照';


--
-- Name: COLUMN relay_usage_record.price_tier_min_input_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.price_tier_min_input_tokens IS '本次请求适用的价格阶梯最小输入Token数快照';


--
-- Name: COLUMN relay_usage_record.relay_configuration_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.relay_configuration_id IS '本次请求最终成功使用的中转站ID；历史数据或未到达上游时为NULL';


--
-- Name: COLUMN relay_usage_record.requested_model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.requested_model_id IS '下游客户端传入的模型显示文本；未传入时保存平台最终选定的模型显示名称';


--
-- Name: COLUMN relay_usage_record.upstream_model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.upstream_model_id IS '本服务按中转站模型映射实际发送给上游的模型ID；上游仍可能在内部再次路由';


--
-- Name: COLUMN relay_usage_record.reported_model_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.reported_model_id IS '上游响应model字段明确声明的模型ID；上游未返回时为NULL，禁止用发送模型冒充';


--
-- Name: COLUMN relay_usage_record.upstream_model_source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.upstream_model_source IS '真实执行模型判定来源：RESPONSE表示上游响应明确声明，CONFIG表示仅能确认直连配置，UNKNOWN表示无法确认';


--
-- Name: COLUMN relay_usage_record.protocol_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.relay_usage_record.protocol_code IS '本次请求在首个输出前最终选定的上游协议';


--
-- Name: admin_account admin_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.admin_account
    ADD CONSTRAINT admin_account_pkey PRIMARY KEY (username);


--
-- Name: r2_media_files r2_media_files_content_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.r2_media_files
    ADD CONSTRAINT r2_media_files_content_hash_key UNIQUE (content_hash);


--
-- Name: r2_media_files r2_media_files_object_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.r2_media_files
    ADD CONSTRAINT r2_media_files_object_key_key UNIQUE (object_key);


--
-- Name: r2_media_files r2_media_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.r2_media_files
    ADD CONSTRAINT r2_media_files_pkey PRIMARY KEY (id);


--
-- Name: relay_access_group_model relay_access_group_model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_group_model
    ADD CONSTRAINT relay_access_group_model_pkey PRIMARY KEY (group_id, model_id);


--
-- Name: relay_access_group relay_access_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_group
    ADD CONSTRAINT relay_access_group_pkey PRIMARY KEY (id);


--
-- Name: relay_access_token_machine relay_access_token_machine_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_token_machine
    ADD CONSTRAINT relay_access_token_machine_pkey PRIMARY KEY (access_token_id, machine_id);


--
-- Name: relay_access_token relay_access_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_token
    ADD CONSTRAINT relay_access_token_pkey PRIMARY KEY (id);


--
-- Name: relay_access_token relay_access_token_plain_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_token
    ADD CONSTRAINT relay_access_token_plain_unique UNIQUE (token);


--
-- Name: relay_billing_outbox relay_billing_outbox_event_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_billing_outbox
    ADD CONSTRAINT relay_billing_outbox_event_key_key UNIQUE (event_key);


--
-- Name: relay_billing_outbox relay_billing_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_billing_outbox
    ADD CONSTRAINT relay_billing_outbox_pkey PRIMARY KEY (id);


--
-- Name: relay_billing_rule relay_billing_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_billing_rule
    ADD CONSTRAINT relay_billing_rule_pkey PRIMARY KEY (id);


--
-- Name: relay_billing_rule relay_billing_rule_version_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_billing_rule
    ADD CONSTRAINT relay_billing_rule_version_unique UNIQUE (version);


--
-- Name: relay_configuration_model relay_configuration_model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model
    ADD CONSTRAINT relay_configuration_model_pkey PRIMARY KEY (configuration_id, model_id);


--
-- Name: relay_configuration_model_pricing relay_configuration_model_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_pricing
    ADD CONSTRAINT relay_configuration_model_pricing_pkey PRIMARY KEY (id);


--
-- Name: relay_configuration_model_protocol relay_configuration_model_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_protocol
    ADD CONSTRAINT relay_configuration_model_protocol_pkey PRIMARY KEY (id);


--
-- Name: relay_configuration relay_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration
    ADD CONSTRAINT relay_configuration_pkey PRIMARY KEY (id);


--
-- Name: relay_configuration_protocol relay_configuration_protocol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_protocol
    ADD CONSTRAINT relay_configuration_protocol_pkey PRIMARY KEY (id);


--
-- Name: relay_doc_article relay_doc_article_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_article
    ADD CONSTRAINT relay_doc_article_pkey PRIMARY KEY (id);


--
-- Name: relay_doc_article relay_doc_article_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_article
    ADD CONSTRAINT relay_doc_article_slug_key UNIQUE (slug);


--
-- Name: relay_doc_asset relay_doc_asset_object_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_asset
    ADD CONSTRAINT relay_doc_asset_object_key_key UNIQUE (object_key);


--
-- Name: relay_doc_asset relay_doc_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_asset
    ADD CONSTRAINT relay_doc_asset_pkey PRIMARY KEY (id);


--
-- Name: relay_doc_category relay_doc_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_category
    ADD CONSTRAINT relay_doc_category_pkey PRIMARY KEY (id);


--
-- Name: relay_model relay_model_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_model
    ADD CONSTRAINT relay_model_pkey PRIMARY KEY (model_id);


--
-- Name: relay_model_pricing relay_model_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_model_pricing
    ADD CONSTRAINT relay_model_pricing_pkey PRIMARY KEY (id);


--
-- Name: relay_model_pricing relay_model_pricing_version_tier_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_model_pricing
    ADD CONSTRAINT relay_model_pricing_version_tier_unique UNIQUE (model_id, effective_from, min_input_tokens);


--
-- Name: relay_point_ledger relay_point_ledger_event_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_point_ledger
    ADD CONSTRAINT relay_point_ledger_event_key_key UNIQUE (event_key);


--
-- Name: relay_point_ledger relay_point_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_point_ledger
    ADD CONSTRAINT relay_point_ledger_pkey PRIMARY KEY (id);


--
-- Name: relay_token_wallet relay_token_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_token_wallet
    ADD CONSTRAINT relay_token_wallet_pkey PRIMARY KEY (access_token_id);


--
-- Name: relay_usage_record relay_usage_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_usage_record
    ADD CONSTRAINT relay_usage_record_pkey PRIMARY KEY (id);


--
-- Name: relay_usage_record relay_usage_record_request_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_usage_record
    ADD CONSTRAINT relay_usage_record_request_id_key UNIQUE (request_id);


--
-- Name: relay_configuration_model_protocol uq_rcmp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_protocol
    ADD CONSTRAINT uq_rcmp UNIQUE (configuration_id, model_id, protocol_id);


--
-- Name: relay_configuration_model_pricing uq_relay_configuration_model_pricing_version_tier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_pricing
    ADD CONSTRAINT uq_relay_configuration_model_pricing_version_tier UNIQUE (configuration_id, model_id, effective_from, min_input_tokens);


--
-- Name: relay_configuration_protocol uq_relay_configuration_protocol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_protocol
    ADD CONSTRAINT uq_relay_configuration_protocol UNIQUE (configuration_id, protocol_code);


--
-- Name: idx_r2_media_status_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_r2_media_status_updated ON public.r2_media_files USING btree (status, updated_at);


--
-- Name: idx_rcmp_resolve; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rcmp_resolve ON public.relay_configuration_model_protocol USING btree (configuration_id, model_id, enabled, priority);


--
-- Name: idx_relay_access_token_machine_machine; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_access_token_machine_machine ON public.relay_access_token_machine USING btree (machine_id);


--
-- Name: idx_relay_access_token_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_access_token_status ON public.relay_access_token USING btree (status, id);


--
-- Name: idx_relay_billing_rule_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_billing_rule_active ON public.relay_billing_rule USING btree (enabled, effective_from, effective_to);


--
-- Name: idx_relay_configuration_dispatch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_dispatch ON public.relay_configuration USING btree (enabled, health_status, priority, id);


--
-- Name: idx_relay_configuration_model_configuration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_model_configuration ON public.relay_configuration_model USING btree (configuration_id, enabled, model_id);


--
-- Name: idx_relay_configuration_model_dispatch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_model_dispatch ON public.relay_configuration_model USING btree (model_id, enabled, configuration_id);


--
-- Name: idx_relay_configuration_model_pricing_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_model_pricing_lookup ON public.relay_configuration_model_pricing USING btree (configuration_id, model_id, enabled, effective_from, effective_to);


--
-- Name: idx_relay_configuration_model_pricing_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_model_pricing_model ON public.relay_configuration_model_pricing USING btree (model_id, enabled);


--
-- Name: idx_relay_configuration_protocol_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_configuration_protocol_lookup ON public.relay_configuration_protocol USING btree (configuration_id, enabled, priority);


--
-- Name: idx_relay_doc_article_category_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_doc_article_category_sort ON public.relay_doc_article USING btree (category_id, sort_order, id);


--
-- Name: idx_relay_doc_article_public; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_relay_doc_article_public ON public.relay_doc_article USING btree (status, category_id, sort_order);


--
-- Name: relay_access_token_group_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_access_token_group_idx ON public.relay_access_token USING btree (group_id);


--
-- Name: relay_billing_outbox_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_billing_outbox_pending_idx ON public.relay_billing_outbox USING btree (status, next_attempt_at, id);


--
-- Name: relay_model_pricing_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_model_pricing_lookup_idx ON public.relay_model_pricing USING btree (model_id, enabled, effective_from, effective_to);


--
-- Name: relay_point_ledger_request_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_point_ledger_request_idx ON public.relay_point_ledger USING btree (request_id);


--
-- Name: relay_point_ledger_token_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_point_ledger_token_created_idx ON public.relay_point_ledger USING btree (access_token_id, created_at);


--
-- Name: relay_usage_record_configuration_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_usage_record_configuration_created_idx ON public.relay_usage_record USING btree (relay_configuration_id, created_at);


--
-- Name: relay_usage_record_group_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_usage_record_group_created_idx ON public.relay_usage_record USING btree (group_id, created_at);


--
-- Name: relay_usage_record_model_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_usage_record_model_created_idx ON public.relay_usage_record USING btree (model_id, created_at);


--
-- Name: relay_usage_record_reported_model_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_usage_record_reported_model_created_idx ON public.relay_usage_record USING btree (reported_model_id, created_at);


--
-- Name: relay_usage_record_token_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX relay_usage_record_token_created_idx ON public.relay_usage_record USING btree (access_token_id, created_at);


--
-- Name: relay_configuration_model_protocol fk_rcmp_model_route; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_protocol
    ADD CONSTRAINT fk_rcmp_model_route FOREIGN KEY (configuration_id, model_id) REFERENCES public.relay_configuration_model(configuration_id, model_id) ON DELETE CASCADE;


--
-- Name: relay_configuration_model_protocol fk_rcmp_protocol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_protocol
    ADD CONSTRAINT fk_rcmp_protocol FOREIGN KEY (protocol_id) REFERENCES public.relay_configuration_protocol(id) ON DELETE CASCADE;


--
-- Name: relay_configuration_model fk_relay_configuration_model_configuration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model
    ADD CONSTRAINT fk_relay_configuration_model_configuration FOREIGN KEY (configuration_id) REFERENCES public.relay_configuration(id) ON DELETE CASCADE;


--
-- Name: relay_configuration_model fk_relay_configuration_model_model; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model
    ADD CONSTRAINT fk_relay_configuration_model_model FOREIGN KEY (model_id) REFERENCES public.relay_model(model_id) ON DELETE CASCADE;


--
-- Name: relay_configuration_model_pricing fk_relay_configuration_model_pricing_relation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_model_pricing
    ADD CONSTRAINT fk_relay_configuration_model_pricing_relation FOREIGN KEY (configuration_id, model_id) REFERENCES public.relay_configuration_model(configuration_id, model_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: relay_configuration_protocol fk_relay_protocol_configuration; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_configuration_protocol
    ADD CONSTRAINT fk_relay_protocol_configuration FOREIGN KEY (configuration_id) REFERENCES public.relay_configuration(id) ON DELETE CASCADE;


--
-- Name: relay_access_group_model relay_access_group_model_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_group_model
    ADD CONSTRAINT relay_access_group_model_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.relay_access_group(id) ON DELETE CASCADE;


--
-- Name: relay_access_group_model relay_access_group_model_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_group_model
    ADD CONSTRAINT relay_access_group_model_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.relay_model(model_id) ON DELETE CASCADE;


--
-- Name: relay_access_token relay_access_token_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_token
    ADD CONSTRAINT relay_access_token_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.relay_access_group(id);


--
-- Name: relay_access_token_machine relay_access_token_machine_access_token_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_access_token_machine
    ADD CONSTRAINT relay_access_token_machine_access_token_id_fkey FOREIGN KEY (access_token_id) REFERENCES public.relay_access_token(id) ON DELETE CASCADE;


--
-- Name: relay_billing_outbox relay_billing_outbox_request_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_billing_outbox
    ADD CONSTRAINT relay_billing_outbox_request_fk FOREIGN KEY (request_id) REFERENCES public.relay_usage_record(request_id) ON DELETE CASCADE;


--
-- Name: relay_doc_article relay_doc_article_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_article
    ADD CONSTRAINT relay_doc_article_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.relay_doc_category(id) ON DELETE CASCADE;


--
-- Name: relay_doc_asset relay_doc_asset_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_doc_asset
    ADD CONSTRAINT relay_doc_asset_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.relay_doc_article(id) ON DELETE SET NULL;


--
-- Name: relay_point_ledger relay_point_ledger_token_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_point_ledger
    ADD CONSTRAINT relay_point_ledger_token_fk FOREIGN KEY (access_token_id) REFERENCES public.relay_access_token(id) ON DELETE CASCADE;


--
-- Name: relay_token_wallet relay_token_wallet_token_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_token_wallet
    ADD CONSTRAINT relay_token_wallet_token_fk FOREIGN KEY (access_token_id) REFERENCES public.relay_access_token(id) ON DELETE CASCADE;


--
-- Name: relay_usage_record relay_usage_record_configuration_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_usage_record
    ADD CONSTRAINT relay_usage_record_configuration_fk FOREIGN KEY (relay_configuration_id) REFERENCES public.relay_configuration(id) ON DELETE SET NULL;


--
-- Name: relay_usage_record relay_usage_record_group_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_usage_record
    ADD CONSTRAINT relay_usage_record_group_fk FOREIGN KEY (group_id) REFERENCES public.relay_access_group(id);


--
-- Name: relay_usage_record relay_usage_record_token_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.relay_usage_record
    ADD CONSTRAINT relay_usage_record_token_fk FOREIGN KEY (access_token_id) REFERENCES public.relay_access_token(id);


--
