-- 路由级（中转站 × 模型）的推理强度裁决。三态：
--   NULL  = 自动，跟随运行期学到的结果（Redis 否定标记）
--   FALSE = 管理员确认不支持，永不下发该参数
--   TRUE  = 管理员确认支持，忽略自动标记（用于纠正误判）
ALTER TABLE public.relay_configuration_model
    ADD COLUMN reasoning_enabled boolean;

COMMENT ON COLUMN public.relay_configuration_model.reasoning_enabled IS
    '该中转站上此模型是否支持推理强度：NULL 自动学习 / FALSE 确认不支持 / TRUE 确认支持并忽略自动标记';

-- 共识达成后沉淀给管理员看的告警。
-- 为什么落库而不是只放 Redis：Redis 里的计数是可丢的学习过程，而「已经提示过管理员」
-- 这件事必须能在重启后继续存在，否则告警会反复出现或凭空消失。
CREATE TABLE public.relay_reasoning_alert (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    configuration_id bigint NOT NULL,
    model_id character varying(255) NOT NULL,
    protocol_code character varying(64) NOT NULL,
    upstream_model_id character varying(255) NOT NULL,
    kind character varying(16) NOT NULL,
    source_count integer DEFAULT 0 NOT NULL,
    first_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT pk_relay_reasoning_alert PRIMARY KEY (id),
    CONSTRAINT uq_relay_reasoning_alert_route UNIQUE (configuration_id, model_id, protocol_code, kind),
    CONSTRAINT ck_relay_reasoning_alert_kind CHECK (kind IN ('REJECTED', 'IGNORED')),
    CONSTRAINT ck_relay_reasoning_alert_protocol CHECK (protocol_code IN
        ('OPENAI_CHAT_COMPLETIONS', 'OPENAI_RESPONSES', 'ANTHROPIC_MESSAGES'))
);

COMMENT ON TABLE public.relay_reasoning_alert IS '推理强度不生效的路由告警，REJECTED 为已确认拒绝，IGNORED 为疑似被静默忽略';
COMMENT ON COLUMN public.relay_reasoning_alert.kind IS
    'REJECTED=上游明确拒绝该参数（事实，已自动降级）；IGNORED=请求了中高档位但未产生 reasoning token（怀疑，需人工核实）';
COMMENT ON COLUMN public.relay_reasoning_alert.source_count IS '触发该告警的独立 Token 数，用于区分单用户异常与普遍现象';
COMMENT ON COLUMN public.relay_reasoning_alert.resolved_at IS '管理员处理时间；再次出现时会被重置为 NULL';

CREATE INDEX ix_relay_reasoning_alert_open ON public.relay_reasoning_alert (resolved_at, last_seen_at DESC);
